export const data = [
    {
        "type": "Feature",
        "properties": {
            "id": "relation/67773",
            "access": null,
            "alt_name": null,
            "castle_type": "defensive;stately",
            "historic": "castle",
            "name": "Grazer Burg",
            "ruins": null,
            "start_date": null,
            "tourism": null,
            "website": null,
            "wikidata": "Q874547",
            "wikimedia_commons": "Category:Grazer Burg",
            "wikipedia": "de:Grazer Burg",
            "location": "Graz",
            "time of origin": "1438",
            "description-translated": "The Graz castle is located in the east of the old town of Graz, near the Graz Cathedral, and was built from 1438 by Duke Friedrich V, later Roman-German Emperor Friedrich III. Due to the low defense value, the castle was connected to the fortress on Schloßberg via a hidden gait. From 1564 Graz was the capital inner Austria and the castle became the seat of the Inner -Austrian Archduke. Because of this position, it was rebuilt and enlarged. After Archduke Ferdinand II was crowned the emperor in 1619 and moved to Vienna, the castle lost its function as the seat of the sovereign and was neglected.",
            "image url": "https://de.wikipedia.org/wiki/Datei:Burg_AZ3_244a.jpg",
            "state": "Steiermark",
            "img_file": "//upload.wikimedia.org/wikipedia/commons/thumb/8/88/Burg_AZ3_244a.jpg/800px-Burg_AZ3_244a.jpg"
        },
        "geometry": { "type": "Point", "coordinates": [15.44233, 47.072855] }
    },
    {
        "type": "Feature",
        "properties": {
            "id": "relation/153258",
            "access": "no",
            "alt_name": null,
            "castle_type": "defensive;stately",
            "historic": "castle",
            "name": "Burg Neulengbach",
            "ruins": null,
            "start_date": null,
            "tourism": null,
            "website": null,
            "wikidata": "Q179236",
            "wikimedia_commons": "Category:Burg Neulengbach",
            "wikipedia": "de:Burg Neulengbach",
            "location": "Gemeinde Neulengbach",
            "time of origin": "around 1189\n(Foundation of the market)",
            "description-translated": "The Neulengbach Castle was a high-altitude castle on a free-standing and around 80 m high mountain cone above the Lower Austrian city of Neulengbach in the Sankt Pölten-Land district, which was converted into a castle in the 16th and 17th centuries. The castle facility is a three -storey multi -corner building with a double weir ring and eight round towers, an stem with a magnificent Renaissance portal and a farm with Tuscan double pillars and stone fountain pools.",
            "image url": "https://de.wikipedia.org/wiki/Datei:Neulengbach_-_Schloss.JPG",
            "state": "Niederösterreich",
            "img_file": "//upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Neulengbach_-_Schloss.JPG/800px-Neulengbach_-_Schloss.JPG"
        },
        "geometry": { "type": "Point", "coordinates": [15.91035, 48.198384] }
    },
    {
        "type": "Feature",
        "properties": {
            "id": "relation/272568",
            "access": null,
            "alt_name": null,
            "castle_type": "defensive",
            "historic": "castle",
            "name": "Schloss Ulmerfeld",
            "ruins": null,
            "start_date": null,
            "tourism": null,
            "website": null,
            "wikidata": "Q2243794",
            "wikimedia_commons": "Category:Schloss Ulmerfeld",
            "wikipedia": "de:Schloss Ulmerfeld",
            "location": "Gemeinde Amstetten",
            "time of origin": "first mentioned 995",
            "description-translated": "Ulmerfeld Castle is a castle in Ulmerfeld near Amstetten in Lower Austria.",
            "image url": "",
            "state": "Niederösterreich",
            "img_file": null
        },
        "geometry": { "type": "Point", "coordinates": [14.823283, 48.076931] }
    },
    {
        "type": "Feature",
        "properties": {
            "id": "relation/1244836",
            "access": null,
            "alt_name": null,
            "castle_type": "defensive",
            "historic": "castle",
            "name": "Burg Schlaining",
            "ruins": null,
            "start_date": null,
            "tourism": "attraction",
            "website": null,
            "wikidata": "Q785923",
            "wikimedia_commons": "Category:Burg Schlaining",
            "wikipedia": "de:Burg Schlaining",
            "location": "Altschlaining",
            "time of origin": "first mentioned 1271",
            "description-translated": "The Friedensburg Schlaining (Hung. Szalónak Vár) is located on the outskirts of Stadtschlaining in Burgenland and was first mentioned in 1271. Only gradually did the name change before it was officially known under its current name in 1786.",
            "image url": "https://de.wikipedia.org/wiki/Datei:Stadtschlaining_-_Burg.JPG",
            "state": "Oberösterreich",
            "img_file": "//upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Stadtschlaining_-_Burg.JPG/800px-Stadtschlaining_-_Burg.JPG"
        },
        "geometry": { "type": "Point", "coordinates": [16.280383, 47.322268] }
    },
    {
        "type": "Feature",
        "properties": {
            "id": "relation/1244840",
            "access": null,
            "alt_name": null,
            "castle_type": "defensive;stately",
            "historic": "castle",
            "name": "Schloss Weinburg",
            "ruins": null,
            "start_date": null,
            "tourism": null,
            "website": null,
            "wikidata": "Q2244026",
            "wikimedia_commons": "Category:Schloss Weinburg am Saßbach",
            "wikipedia": "de:Schloss Weinburg am Saßbach",
            "location": "Sankt Veit in der Südsteiermark",
            "time of origin": "first mentioned 1278",
            "description-translated": "Weinburg Castle is located on a hill in the Murebene in Weinburg am Saßbach, municipality of Sankt Veit in southern Styria in south of Styria on the border with Slovenia.",
            "image url": "",
            "state": "Steiermark",
            "img_file": null
        },
        "geometry": { "type": "Point", "coordinates": [15.719583, 46.754677] }
    },
    {
        "type": "Feature",
        "properties": {
            "id": "relation/1273737",
            "access": null,
            "alt_name": null,
            "castle_type": "defensive",
            "historic": "castle",
            "name": "Burg Wildegg",
            "ruins": null,
            "start_date": null,
            "tourism": null,
            "website": "https://wien.jungschar.at/wildegg",
            "wikidata": "Q1014587",
            "wikimedia_commons": "Category:Burg Wildegg, Sittendorf",
            "wikipedia": "de:Burg Wildegg",
            "location": "Gemeinde Wienerwald",
            "time of origin": "around 1188",
            "description-translated": "The Wildegg Castle is a Felsenburg, south of Vienna, at Sittendorf, south of Vienna, which is used as a youth camp. The owner is the Catholic young of the Archdiocese of Vienna.",
            "image url": "https://de.wikipedia.org/wiki/Datei:Sittendorf_-_Schloss_Wildegg_(c).JPG",
            "state": "Niederösterreich",
            "img_file": "//upload.wikimedia.org/wikipedia/commons/thumb/8/80/Sittendorf_-_Schloss_Wildegg_%28c%29.JPG/800px-Sittendorf_-_Schloss_Wildegg_%28c%29.JPG"
        },
        "geometry": { "type": "Point", "coordinates": [16.165294, 48.086127] }
    },
    {
        "type": "Feature",
        "properties": {
            "id": "relation/1324604",
            "access": null,
            "alt_name": null,
            "castle_type": "defensive",
            "historic": "castle",
            "name": "Festung Hohenwerfen",
            "ruins": null,
            "start_date": null,
            "tourism": "attraction",
            "website": null,
            "wikidata": "Q877023",
            "wikimedia_commons": "Category:Castle_Hohenwerfen",
            "wikipedia": "de:Hohenwerfen",
            "location": "Tenneck",
            "time of origin": "1075 to 1078",
            "description-translated": "The Hohenwerfen fortress is a medieval height castle in Werfen in the Salzburg region between Tennen-, Hagengebirge and Hochkönig in the Salzach Valley.",
            "image url": "https://de.wikipedia.org/wiki/Datei:Festung_Hohenwerfen.jpg",
            "state": "Salzburg",
            "img_file": "//upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Festung_Hohenwerfen.jpg/800px-Festung_Hohenwerfen.jpg"
        },
        "geometry": { "type": "Point", "coordinates": [13.188372, 47.482701] }
    },
    {
        "type": "Feature",
        "properties": {
            "id": "way/122050909",
            "access": null,
            "alt_name": null,
            "castle_type": "defensive",
            "historic": "castle",
            "name": "Burg Hochosterwitz",
            "ruins": null,
            "start_date": null,
            "tourism": "attraction",
            "website": "https://www.burg-hochosterwitz.com",
            "wikidata": "Q679248",
            "wikimedia_commons": "Category:Burg Hochosterwitz",
            "wikipedia": "de:Burg Hochosterwitz",
            "location": "Launsdorf",
            "time of origin": "around 860",
            "description-translated": "The Hochosterwitz Castle is a Höhenburg in the municipality of St. Georgen am Längsee. It is a landmark and a sight of the Austrian state of Carinthia.",
            "image url": "https://de.wikipedia.org/wiki/Datei:St._Georgen_am_L%C3%A4ngsee_-_Burg_Hochosterwitz_(c).JPG",
            "state": "Kärnten",
            "img_file": "//upload.wikimedia.org/wikipedia/commons/thumb/1/17/St._Georgen_am_L%C3%A4ngsee_-_Burg_Hochosterwitz_%28c%29.JPG/800px-St._Georgen_am_L%C3%A4ngsee_-_Burg_Hochosterwitz_%28c%29.JPG"
        },
        "geometry": { "type": "Point", "coordinates": [14.452341, 46.755924] }
    }
];